name: Test
"on":
  workflow_dispatch: null
  pull_request: null
  push: null
jobs:
  pr-test:
      strategy:
        matrix:
          os:
            - ubuntu-latest
      runs-on: ${{ matrix.os }}
      steps:
        - run: cd perl_genrule_problem && bazel test //...
    